namespace Assets.Scripts.User.Ad
{
	public enum UserAdType
	{
		NONE = 0,
		
		AD_BANNER = 13,
		AD_INTERSTITIAL = 12,
		
		AD_UNIVERSAL_SERVER_POINT = 999,
		
		AD_MONEY1 = 1,
		AD_MONEY2 = 2,
		AD_MONEY3 = 3,
		AD_SPECIAL1 = 4,
		AD_SPECIAL2 = 5,
		AD_SPECIAL3 = 6,
		AD_SPECIAL4 = 7,
		AD_SPECIAL5 = 8,
		AD_SPECIAL7 = 9,
		
		QUEST_REWARD_DOUBLE = 10,
		FACTORY_REWARD_DOUBLE = 17,
		DAILY_QUEST_DOUBLE = 18,
		UNIT_QUEST_DOUBLE = 19,
		
		AD_BOOST_SPEEDUP = 11,
		AD_BOOST_CATCH = 14,
		AD_BOOST_XP = 15,
		AD_BOOST_MONEY1 = 16,
		
		
		AD_APP_OPEN = 20,
		
		AD_NATIVE_BANNER_UPGRADES = 101,
		AD_NATIVE_BANNER_UPGRADE_MARKET = 102,
		AD_NATIVE_BANNER_BOT_SHOP = 103,
		AD_NATIVE_BANNER_FACTORY_1 = 104,
		AD_NATIVE_BANNER_FACTORY_3 = 105,
		AD_NATIVE_BANNER_FACTORY_4 = 106,
		AD_NATIVE_BANNER_DAILY_QUESTS = 107,
		AD_NATIVE_BANNER_BANK = 108,
		AD_NATIVE_BANNER_SHIP_QUEST = 109,
		AD_NATIVE_BANNER_SHIP_CHILD_QUEST = 110,
	}
}